from ..types import CycleRule


MAX_DRIVING_HOURS_PER_DAY = 11
MAX_DUTY_WINDOW_HOURS = 14
REQUIRED_REST_HOURS = 10
BREAK_AFTER_DRIVING_HOURS = 8
BREAK_DURATION_HOURS = 0.5
FUEL_STOP_EVERY_MILES = 1000
FUEL_STOP_DURATION_HOURS = 0.5
PICKUP_DURATION_HOURS = 1
DROPOFF_DURATION_HOURS = 1
AVERAGE_SPEED_MPH = 55
MAX_PLANNING_DAYS = 30
FLOAT_EPSILON = 1e-9

CYCLE_RULES: dict[CycleRule, dict[str, int]] = {
    "70_8": {"max_hours": 70, "days": 8},
    "60_7": {"max_hours": 60, "days": 7},
}
